### ISSUE TITLE
Using with razor pages

### ISSUE THREAD

**Issue by dehghani-mehdi** [mikebrind/RazorEngineViewOptionsFileProviders#1]
Hi,

I read your article, it's really helpful. thank you.
I'm wondering what part(s) should I change, add, remove if I want to apply this solution in Razor page project?

**Comment by mikebrind** [comment]
I'm not sure that this will work for Razor Pages - certainly not for 2.2. RP scans folders (Pages) for physical files for routing when the application starts.  There doesn't seem to be any way to fool the framework into seeing a database as a directory.

There's some relevant discussion here: https://github.com/aspnet/Mvc/issues/6489
