### ISSUE TITLE
May I ask if this method is applicable Is NET8 still applicable?

### ISSUE THREAD

**Issue by sqlnew** [mikebrind/RazorEngineViewOptionsFileProviders#4]
This plan is very useful, it's great,
I am currently using it NET8, I wonder if this method is still applicable? In the latest Razor Page project, are there any other areas that need to be modified? Thank you very much.

**Comment by mikebrind** [comment]
Sure, this should still work in .Net 8 as far as I'm aware. I don't believe there have been any breaking changes to the underlying framework in the last 8 years. Have you tried it?

**Comment by sqlnew** [comment]
First of all, thank you very much for your reply, although this code has been around for many years.

I found this code information because I am using the latest Asp We encountered an issue with Net Core 8 Razor Page technology. I want to directly modify the csHTML file without recompiling the entire program after the website is published, so I followed the tutorial and used Razor's dynamic compilation technique, using AddRazorRuntimeCompilation for dynamic compilation of RazorPage. At first, it was normal and working well, but when I published the program in single file mode and accessed the Razor Page page address, the program made an error. It seems that the program cannot find the correct csHTML file and cannot be dynamically compiled. I tried various methods but couldn't solve it. Later, while dynamically debugging and executing the program, I found that it was likely due to an issue with the IFileProvider section. Therefore, I have decided to directly use the specified csHTML file data source to try and see if it can solve the problem. For example, reading csHTML files from a database for dynamic compilation.

I'm not sure if you can provide a solution, I really appreciate it!

Additionally, I have submitted this issue to the official website of asp.net, but so far, there has been no response, which is very frustrating.

Address for submitting bugs:
https://github.com/dotnet/aspnetcore/issues/54315

**Comment by sqlnew** [comment]
This problem has been successfully solved!
